### ISSUE TITLE
ImportError: No module named setuptools

### ISSUE THREAD

**Issue by yafp** [jeena/FeedTheMonkey#1]
Just downloaded the current master, extracted it, installed pyqt5-dev-tools pyqt5-dev and then tried running:

>> sudo python setup.py install

which ends up with the following error:

>> Traceback (most recent call last):
>>  File "setup.py", line 4, in <module>
>>    from setuptools import setup
>> ImportError: No module named setuptools

Could you give me a hand what i am doing wrong here?

**Comment by jeena** [comment]
I have rewritten the whole application in C++ and QML instead of python. I hope this will be easier to install too. Because of that this issue has been invalidated and I am closing it. The code is still accessible in a branch here but I will not invest time into it anymore.
