### ISSUE TITLE
Compiled Binaries? (with compliation service suggestions)

### ISSUE THREAD

**Issue by MichaelTunnell** [jeena/FeedTheMonkey#12]
I realize providing compiled binaries is a giant pain in the butt, especially Linux binaries because there are so many distros and package implementations.

However, I think it would get a lot more attention if binaries were provided. I realize that seems silly since TT-RSS is only utilized by people with technical skill to do so but version management with TT-RSS is just git pulls where as this would require repeated compiling with no package management notification of updates so it would be a manual task to do it.

Any chance you'd be willing to do binaries?

openSUSE's Open Build Service (OBS):
http://openbuildservice.org/
Supports compiling binaries for Arch, CentOS, Debian, Fedora, Mageia, openSUSE, RHEL, ScientificLinux, SLE, Ubuntu, and Univention.

Ubuntu's Launchpad:
https://launchpad.net/
Automated package compiling for PPAs on all supported Ubuntu releases and derivatives.

----------------

Or alternatively it would be cool to have a Snap, Flatpak, and/or AppImage for it . . . if you don't want to worry about compiling and distributing a plethora of packages.

**Comment by jeena** [comment]
It would be cool, I could look into OBS when I have the time.

**Comment by orschiro** [comment]
That would be totally great to have an Ubuntu binary! :-)

Maybe Flatpak or Snaps could be used here, too, alternatively?

**Comment by jeena** [comment]
Someone contributed some code for AppImage yesterday already, I just didn't have the time to read and understand how this actually works. I would like to see that there also is a way to upgrade, etc.

**Comment by MichaelTunnell** [comment]
> Someone contributed some code for AppImage yesterday already,

That is pretty cool.

> I just didn't have the time to read and understand how this actually works. I would like to see that there also is a way to upgrade, etc.

AppImages are not upgradeable via package managers. They work in an "all in one" approach so all of the dependencies needed to run an app are included in the AppImage.

The process of upgrading AppImages is VERY easy even though it's not integrated.

When you launch an AppImage it asks you if you want to create a menu item or not so that it will be in your system menu. It also integrates with your /home for settings and app-data.

The most important part is the /home integration because it means that to upgrade an AppImage, all you have to do is delete the old AppImage and download the new one. All settings and such are saved separately.

I think the only potential issue is the location of where the AppImage is placed before running. This would only effect the menu though not the settings.

--------------

If you want to learn about Ubuntu's Snaps and Snappy, I made a video about it: https://youtu.be/0ApRUndiXKU

I also plan to make a video about Flatpaks and AppImages. :)

**Comment by probonopd** [comment]
> Someone contributed some code for AppImage yesterday already

If you like the AppImages, then maybe you'd like to put them on the GitHub Releases page where people can actually find them (rather than just having the link in the Travis CI build logs). Or could use something like https://github.com/probonopd/uploadtool

**Comment by jeena** [comment]
Yeah I will, just didn't have the time yet and the hotel wifi is really shitty so I have a hard time to load webpages successfully. I'll be home next week and there hopefully I get it done.

**Comment by orschiro** [comment]
Thank you for your great work, Jeena!

**Comment by jeena** [comment]
Ok, thanks to @probonopd pull request Travis-CI now builds a AppImage and I'm putting it up on https://github.com/jeena/FeedTheMonkey/releases/latest as a binary for everyone to use. I think it should work nicely on all distributions. The only bad thing is that it's 70 Mb big, but I guess it's better than having to download the Qt SDK to compile it yourself.

**Comment by orschiro** [comment]
Fantastic. Thank you so much, @jeena! :-)
