### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by nielsmde** [jeena/FeedTheMonkey#13]
Hi,

I just ran across this neat app and wanted to try it out. I am able to successfully compile the application but then when prompted with the login screen, I enter my tt-rss server and the credentials but nothing happens when I click Ok.

I'm running Fedora 25, with the package qt5-devel installed

> Installed Packages
> Name        : qt5-devel
> Arch        : noarch
> Epoch       : 0
> Version     : 5.7.1
> Release     : 1.fc25
> Size        : 25  
> Repo        : @System
> From repo   : updates
> Summary     : Qt5 meta devel package
> URL         : https://getfedora.org/
> License     : GPLv3
> Description : Qt5 meta devel package.

What I did:

    $ git clone git@github.com:jeena/FeedTheMonkey.git
    $ cd FeedTheMonkey
    $ qmake-qt5
    $ make
    $ ./feedthemonkey

Any suggestions how to get it working?
Or is this a problem with Qt 5.7?
I also tried to run it with QtCreator, with the same result.

Niels

**Comment by nielsmde** [comment]
Sorry I just realized this was not a problem with feedthemonkey but the API access was disabled server side. Some gui feedback in such cases would be helpfull.

**Comment by jeena** [comment]
Hm yeah you're right, the error handling is not really good yet and should be handled better, especially during the first steps. Would you mind to open a new issue for that?
