### ISSUE TITLE
Add Night Mode

### ISSUE THREAD

**Issue by cwmke** [jeena/FeedTheMonkey#7]
So far this is just what I was looking for!  Thanks for making this.  I'm wondering if you have any interest in adding a night mode so that it has a dark background (black or dark gray) with light colored text?  Thanks either way.

**Comment by jeena** [comment]
That is not a bad idea actually, I'm not sure when I will have the time to do that but I will update it here when it's done.

**Comment by jeena** [comment]
I implemented this now, I'm not 100% sure about the colors, if you have better colors than we can change them.
